language: android
dist: precise

env:
  global:
    - secure: "jjkUBOfMEs4AA/F/4NlQj0G67t3WW98NP6RQ27rNSlfE0kyrWnVGNkNZAOauavJ/0JMB1ErmYEi5fGm+9GbXm+CWleUNEmUxHlhubwVtFk8sj5SbOs0xp9fpxk65sLif0zRT3d/3eol1zofpoXASB0WtmrNr4mbMXVSA5JXyM2goqD2Qk2ABk/leE+hxODLAkUhc9roCYslst7IhtZcU55kwx25w0LOaXwtSJfrt51l2OtLv1edcifSSU7JUJRlirvUAX7cpvn/8Jb0lgNzuoXFSsrMja9uXyHJxRa5fNGNM5SgLuZC6jw7FBuEKj2sGUL1OdrOXDi8qZoEOtEvMNTe+qORr+He3Ecq8Bg3ZAF0ZisJ6YETT/Kr7ixySHdsK+xqTvB2yx0QQbPcrACSbqtBiOigyVYaWOz0WFMbnF5aIkGBwUusPPWYmQCn28nSPkvAQsrOyGWBPvnU7zZCFbDaQTVb66TKtM2FT5c3XbsVKuwbJG1K+HdnFfoz+ZxK8En40718+ghRK06mij4iSMnSBqZ8g3cTZXZ6tDE7qpzDFXynIThZE2RtKhGwuC4Cpjl/cZauN0sdBn1FfXtCA8nF04oICltNz0bz+rZjgLAeknIx32P2q4f+g5F1kObBECjfum6StZ9JkdJiTb93bAbqtSDgScexTuAV4cs9KtmE="
    - secure: "P1ckY6Qafvzvilw0ORiHzmzdDfw+wFxg4PW6/0+kKuaVoM9dbYQuVP5zNHOQXJCAJXAU79mLAePenrv5b65p9UJSNnjJz3yjAj5rKcF+Ynu3qhxSNp4BRQF+KpXBrr1Hz5yHGxA5P9p7Yk11TstU9l2vvQO4TRJYq33gqUfr66wFJRQpT6TMzdrgXn55YX+2/aQM/9dEhDDA3PMnn1haHseMb9wiyrQ9aYYcbcptXNoZnf4i0uzFvuZFLtSxkk/32PPT0r7rZN5jiZd0WmEgZ8cg+BqItNMGOvFxa9U1+NtP6aOMv8fvJTYQAsWj+vtKaNCIcLrr+njKPxAJ4TomwN6CBJgaFGxH+xtGlQw/HtLxrKCWCPEJpZdCGb6iR2x/cS6Juhm7CnrrLDXC68x7aSkaiGQQPqu2cYtahEm3niuBbfYSubVqPqNcQQxcpjftXemlUszlWBSRmkJL7DvUI74djaICz8L6UCNzl4eRsGPztejtp3OJS3/IHYVK0udyKCJfGbyDWFRCiPCkkfhHeJarea/2zzlMCnYx3ZgAiyMD3H6vfmC7S5YdA0Y8KKDQYycQ5+VHq02LoFjycT7k/zvUmidB0umqNfgd2qK4Dz41BU6fjjB/1N3qP3MGlRS8Mg0a68j3hOihbZw21rIqfvIVFeq8BO2Yyd7ferThbvg="
    - secure: "edBQkqWeIcG0q/q+XdSZj4tfrvZJvbBAR2xDDnmvDbOyKLs8VRe6vlAE+j09N3WyM5vaeYRWotvguugcHpg484fovfA/8Y8r5QV7676jnCWINruDXDzfTy72VPBEdiz15076DMd4sE89tbYhT66xv1mxHvAYkq8K1XTJQ+OPXfc+Fqpic5HTpATrkhShMkiimwS+LfO0wyUY/JxOtXqn9qVtZwnWoQTFr01GeKtXnWWwBSH85ipp7hV6Ozv9qVflsL3p13iNWYdhuhBQ5CxkzUaBHxePuZwmK4b+szZa8R4qh03lFnnlsFkW9WKVSwclcoo8sbPEmypa1eNE94LA2FGNn91XKZkCiA8DRPCBTJBSoaet7NZ+GJE3axj1OvG2NjBypvMqRyeAqFryvRJoUeAAMOIHVYDyoBKtc6aJ+z1ECG7fj9VARfqJoseGLeIpdbxpU9vPx6Evbjzj4K31XQZS0HNp5/p5KFXZ7EU88XaAZkVKqFgZJq1+6VOgjH6Lg1dq34gPuC6f+IlemYzX3Ib4TS3ZaSk8AjcMqDDvVlVTvsVVnPZ7nkJTWgAXywx1tk8+RkDSqViCIsKAFDFTnuJLZiv0zysbHzQMJYCKTfukN5xqvjOPBSSvnn6iO8m24eHDRPIktpSO7hCXNknpQ6H90pj7ZiENaDmDbDdh/ho="

android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    - extra-android-m2repository

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - . ./ci/prepare_env_travis.sh
  - ./ci/run_unit_tests.sh



