steps:
  - label: 'Upload App Distribution Internal'
    if: build.branch == "master" || build.branch =~ /^v[0-9]+.*/
    #TODO: rename key here and on build server to upload-app-distribution (buildkite agent hooks)
    key: 'upload-firebase'
    command: 'ci/upload_app_distribution.sh internal-beta internal'

  - label: 'Upload Github Release'
    if: build.branch =~ /^v[0-9]+.*/
    key: 'upload-github'
    command: 'ci/upload_to_github.sh'

